In [1]:
import numpy as np

A = np.array([[0, 1], [2, 3], [4, 5]])

B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

C = np.dot(A, B)  # または C = A @ B

print("行列の積 C:")
print(C)

max_value = C.max()
print("行列 C の最大値:")
print(max_value)

行列の積 C:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列 C の最大値:
47
